CREATE TABLE IF NOT EXISTS tshirts(
id INTEGER PRIMARY KEY,
quantity INTEGER,
price INTEGER,
img_url TEXT
);

CREATE TABLE IF NOT EXISTS transactions(
id INTEGER PRIMARY KEY,
email TEXT,
tshirt_id INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);